import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "@/containers/HomePage";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homestead</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <HomePage />
      </main>
    </div>
  );
};

export default Home;
