import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "@/containers/HomePage";
import PropertyListing from "@/components/PropertyListing";
import { listings } from "@/utils/dummyListings";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homestead</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <HomePage />
        <div className="flex flex-col items-center mt-6 space-y-4">
          {listings.map(
            ({ id, location, images, bathrooms, bedrooms, area, title , price}) => (
              <PropertyListing
                key={id}
                title={title}
                location={location}
                price={price}
                image={images[0].original}
                id={id}
                bedrooms={bedrooms}
                bathrooms={bathrooms}
                area={area}
              />
            )
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
