import type { NextPage } from "next";
import Head from "next/head";
import HomePageContainer from "@/containers/HomePageContainer";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homestead</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col min-h-screen">
        <div className="flex-grow container">
          <Navbar />
          <HomePageContainer />
        </div>
        <Footer />
      </main>
    </div>
  );
};

export default Home;
